apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-adminer
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-adminer
  template:
    metadata:
      labels:
        app: todo-adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-adminer
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: todo-adminer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32081
