apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: rbaldiviezo/todo_backend:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: todo-db
            - name: POSTGRES_USER
              value: todo_user
            - name: POSTGRES_PASSWORD
              value: todo_pass
            - name: POSTGRES_DB
              value: todo_db
            - name: LOGGER_URL
              value: http://todo-logger:4000/log
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  type: LoadBalancer
  selector:
    app: todo-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
